// <auto-generated />
using System;
using BinksNoSake.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinksNoSake.Persistence.Migrations
{
    [DbContext(typeof(BinksNoSakeContext))]
    [Migration("20231118142701_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("BinksNoSake.Domain.Models.CapitaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimoneiroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimoneiroId")
                        .IsUnique();

                    b.ToTable("Capitaes");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.NavioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PirataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PirataId");

                    b.ToTable("Navios");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.PirataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapitaoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataIngressoTripulacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Funcao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapitaoId");

                    b.ToTable("Piratas");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.TimoneiroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapitaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Timoneiros");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.CapitaoModel", b =>
                {
                    b.HasOne("BinksNoSake.Domain.Models.TimoneiroModel", "Timoneiro")
                        .WithOne("Capitao")
                        .HasForeignKey("BinksNoSake.Domain.Models.CapitaoModel", "TimoneiroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Timoneiro");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.NavioModel", b =>
                {
                    b.HasOne("BinksNoSake.Domain.Models.PirataModel", "Pirata")
                        .WithMany("Navios")
                        .HasForeignKey("PirataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pirata");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.PirataModel", b =>
                {
                    b.HasOne("BinksNoSake.Domain.Models.CapitaoModel", "Capitao")
                        .WithMany("Piratas")
                        .HasForeignKey("CapitaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Capitao");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.CapitaoModel", b =>
                {
                    b.Navigation("Piratas");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.PirataModel", b =>
                {
                    b.Navigation("Navios");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.TimoneiroModel", b =>
                {
                    b.Navigation("Capitao");
                });
#pragma warning restore 612, 618
        }
    }
}
