// <auto-generated />
using System;
using BinksNoSake.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinksNoSake.Persistence.Migrations
{
    [DbContext(typeof(BinksNoSakeContext))]
    partial class BinksNoSakeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("BinksNoSake.Domain.Models.CapitaoModel", b =>
                {
                    b.Property<int>("CapitaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimoneiroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CapitaoId");

                    b.ToTable("Capitaes");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.NavioModel", b =>
                {
                    b.Property<int>("NavioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PirataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NavioId");

                    b.HasIndex("PirataId");

                    b.ToTable("Navios");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.PirataModel", b =>
                {
                    b.Property<int>("PirataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapitaoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataIngressoTripulacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Funcao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .HasColumnType("TEXT");

                    b.HasKey("PirataId");

                    b.HasIndex("CapitaoId");

                    b.ToTable("Piratas");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.TimoneiroModel", b =>
                {
                    b.Property<int>("TimoneiroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapitaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("TimoneiroId");

                    b.HasIndex("CapitaoId")
                        .IsUnique();

                    b.ToTable("Timoneiros");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.NavioModel", b =>
                {
                    b.HasOne("BinksNoSake.Domain.Models.PirataModel", "Pirata")
                        .WithMany("Navios")
                        .HasForeignKey("PirataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pirata");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.PirataModel", b =>
                {
                    b.HasOne("BinksNoSake.Domain.Models.CapitaoModel", "Capitao")
                        .WithMany("Piratas")
                        .HasForeignKey("CapitaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Capitao");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.TimoneiroModel", b =>
                {
                    b.HasOne("BinksNoSake.Domain.Models.CapitaoModel", "Capitao")
                        .WithOne("Timoneiro")
                        .HasForeignKey("BinksNoSake.Domain.Models.TimoneiroModel", "CapitaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Capitao");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.CapitaoModel", b =>
                {
                    b.Navigation("Piratas");

                    b.Navigation("Timoneiro");
                });

            modelBuilder.Entity("BinksNoSake.Domain.Models.PirataModel", b =>
                {
                    b.Navigation("Navios");
                });
#pragma warning restore 612, 618
        }
    }
}
